name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-website-${{ hashFiles('**/Cargo.lock') }}

      - name: Install and Build
        run: |
          cd parser
          yarn install
          yarn ci
