name: Site
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-website-${{ hashFiles('**/Cargo.lock') }}

      - name: Install and Build
        run: |
          cd site
          yarn install
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site/build
